[package]
name = "ch06_06_2_wasm_tomato"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
peg = "0.7"
wasm-bindgen = "0.2"
