[package]
name = "ch05_07_3_web_hello_tide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tide = "0.16"
async-std = {version = "1.8.0", features = ["attributes"]}
